version: '3.9'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbscripts/:/dbscripts/
    env_file:
      - env
    networks:
      - dbnet
  app:
    image: webhello:latest
    volumes:
      - .:/app/
    env_file:
      - env
    depends_on:
      - db
    networks:
      - webnet
      - dbnet
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - webnet
    depends_on:
      - app

networks:
  dbnet:
    driver: bridge
  webnet:
    driver: bridge


volumes:
  postgres_data:

